---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nboard-postgresql-pvc
  namespace: web-cloud
spec:
  storageClassName: cephfs-korbank-ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nboard-postgres
  labels:
    app: nboard-postgres
    developer: rdziwinski
    maintainer: rdziwinski
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdziwinski-postgres
  template:
    metadata:
      labels:
        app: rdziwinski-postgres
    spec:
      containers:
      - name: rdziwinski-postgres
        image: postgres:14-alpine
        envFrom:
          - configMapRef:
              name: postgres-envs
        resources:
          requests:
            cpu: 400m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
        #   failureThreshold: 6
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 5
        #
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/sh
        #     - -c
        #     - -e
        #     - |
        #       exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
        #       [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
        #   failureThreshold: 6
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 5
        ports:
        - containerPort: 5432
          name: tcp-postgresql
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nboard-postgresql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nboard-postgres-svc
spec:
  selector:
    app: nboard-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
