# Generated by Django 4.0.4 on 2022-04-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Announcement'), (1, 'Maintenance'), (2, 'Problem')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('image_title', models.CharField(blank=True, default='Image', max_length=32)),
                ('status', models.IntegerField(choices=[(0, 'Future'), (1, 'In Progress'), (2, 'Archive')], default=0)),
            ],
        ),
    ]
